### ISSUE TITLE
Crash TFCtweaker

### ISSUE THREAD

**Issue by Ashen-sysadmin** [Mrthomas20121/mrthomas20121.github.io#1]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 1/3/21 8:25 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraft.item.ItemStack.getItem()Lnet/minecraft/item/Item;
	at mrthomas20121.tfctweaker.RegistryHandler.onTooltipEvent(RegistryHandler.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_160_RegistryHandler_onTooltipEvent_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:358)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mrthomas20121.tfctweaker.RegistryHandler.onTooltipEvent(RegistryHandler.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_160_RegistryHandler_onTooltipEvent_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:358)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_275, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 3639489584 bytes (3470 MB) / 4953473024 bytes (4724 MB) up to 4953473024 bytes (4724 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4224m -Xmx5120m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version      | Source                                  | Signature                                |
	|:----- |:--------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft       | 1.12.2       | minecraft.jar                           | None                                     |
	| LCH   | mcp             | 9.42         | minecraft.jar                           | None                                     |
	| LCH   | FML             | 8.0.99.99    | forge-1.12.2-14.23.5.2855-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge           | 14.23.5.2855 | forge-1.12.2-14.23.5.2855-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | crafttweaker    | 4.1.20       | CraftTweaker2-1.12-4.1.20.607.jar       | None                                     |
	| LCH   | ctgui           | 1.0.0        | CraftTweaker2-1.12-4.1.20.607.jar       | None                                     |
	| LCH   | mtlib           | 3.0.6        | MTLib-3.0.6.jar                         | None                                     |
	| LCH   | modtweaker      | 4.0.18       | modtweaker-4.0.18.jar                   | None                                     |
	| LCH   | jei             | 4.16.1.302   | jei_1.12.2-4.16.1.302.jar               | None                                     |
	| LCH   | crafttweakerjei | 2.0.3        | CraftTweaker2-1.12-4.1.20.607.jar       | None                                     |
	| LCH   | waila           | 1.8.26       | Hwyla-1.8.26-B41_1.12.2.jar             | None                                     |
	| LCH   | tfc             | 1.7.10.168   | TerraFirmaCraft-MC1.12.2-1.7.10.168.jar | None                                     |
	| LCH   | rocksalt        | 1.0.3        | rocksalt-1.0.3.jar                      | None                                     |
	| LCH   | tfcthings       | 1.3.2        | terrafirmathings-1.3.2.jar              | None                                     |
	| LCH   | tfcmetallum     | 1.4.0        | TFC-Metallum-MC1.12.2-1.4.0.jar         | None                                     |
	| LCH   | tfctech         | 1.2.15       | TFCTech-Unofficial-MC1.12.2-1.2.15.jar  | None                                     |
	| LCH   | tfcompat        | 1.2.0        | tfccompat-1.2.0.jar                     | None                                     |
	| LCH   | tfctweaker      | 1.0.4        | tfctweaker-1.0.4.jar                    | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13497 Compatibility Profile Context 23.20.843.512' Renderer: 'AMD Radeon R7 Graphics'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R7 Graphics GL version 4.5.13497 Compatibility Profile Context 23.20.843.512, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A10-9700 RADEON R7, 10 COMPUTE CORES 4C+6G

**Comment by Ashen-sysadmin** [comment]
CTD while loading minecraft with your mod.

**Comment by Ashen-sysadmin** [comment]
Was this closed because you fixed it?
